# Generated by Django 4.0.4 on 2022-05-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_link', models.URLField(unique=True)),
                ('short_link', models.URLField(blank=True, unique=True)),
                ('clicks', models.IntegerField(default=0, verbose_name='Кол-во кликов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
                'ordering': ['-created_at'],
            },
        ),
    ]
